version: "3"
services:
          #Nginx service
  nginx:
    build: ./nginx
    depends_on:
      - api
      - client
    ports:
      - "3050:80"
  #Postgres database
  postgres_db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=postgres_password
   #Redis database
  redis:
      image: 'redis'
  #Express API
  api:
      build:
        context: ./server
      image: "waquar14/complex_api"
      environment:
          - REDIS_HOST=redis
          - REDIS_PORT=6379
          - PGUSER=postgres
          - PGHOST=postgres_db
          - PGDATABASE=postgres
          - PGPASSWORD=postgres_password
          - PGPORT=5432
  worker:
      build: ./worker
      image: "waquar14/complex_worker"
      environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  client:
       build: ./client
       image: "waquar14/complex_client"

