apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec: 
    selector:
      matchlabels:
        component: web
    template:
      metadata:
        labels:
          component: web
      spec:
        containers:
          -name: client
          image: waquar14/complex_client
          ports:
              -containerPort: 3000
          resources:
              limits:
                memory: "128Mi"
                cpu: "500m"
                